### ISSUE TITLE
tst_shell does not build in Qt 5.2

### ISSUE THREAD

**Issue by equalsraf** [equalsraf/neovim-qt#137]
reported by @BlackEdder, building with Qt 5.2 fails

```
[ 98%] Building CXX object test/CMakeFiles/tst_shell.dir/tst_shell.cpp.o
/home/edwin/Downloads/neovim-qt/test/tst_shell.cpp: In member function ‘void NeovimQt::Test::checkStartVars(NeovimQt::NeovimConnector)’:
/home/edwin/Downloads/neovim-qt/test/tst_shell.cpp:78:60: error: no matching function for call to ‘QSignalSpy::QSignalSpy(NeovimQt::Neovim&, void (NeovimQt::Neovim::*)(QVariant))’
QSignalSpy onVar(nvim, &NeovimQt::Neovim::on_vim_get_var);
^
compilation terminated due to -Wfatal-errors.
```

The alternative QSignalSpy ctor is only available in 5.4 and later.

**Comment by Wouterbeets** [comment]
+1

**Comment by equalsraf** [comment]
We no longer have a CI that targets 5.2, I've started a PR for this. Can anyone with 5.2 check it?

Just in case I've also added a flag to disable unit test building with cmake -DENABLE_TESTS=OFF

**Comment by equalsraf** [comment]
Fixed in master
