### ISSUE TITLE
build failure on macos

### ISSUE THREAD

**Issue by nilsbecker** [equalsraf/neovim-qt#528]
i am not succeeding in getting this to build on mac os 14.4 (with homebrew-installed tools). the `make` step in the installation instruction for unix fails at 23% completion, with:
```
Building CXX object src/gui/shellwidget/CMakeFiles/qshellwidget.dir/qshellwidget_autogen/mocs_compilation.cpp.o
In file included from /Users/nbecker/Code/github/neovim-qt/build/src/gui/shellwidget/qshellwidget_autogen/mocs_compilation.cpp:2:
/Users/nbecker/Code/github/neovim-qt/build/src/gui/shellwidget/qshellwidget_autogen/EWIEGA46WW/moc_shellwidget.cpp:9:10: fatal error:
      '../../../../../../../../../Tresors/Code/github/neovim-qt/src/gui/shellwidget/shellwidget.h' file
      not found
```
The file `shellwidget.h` does exist, but the leading `../` repetitions go to the filesystem root while they should be going to my home directory.

**Comment by equalsraf** [comment]
Hi @nilsbecker 

> i am not succeeding in getting this to build on mac os 14.4 (with homebrew-installed tools). the make step in the installation instruction for unix fails at 23% completion, with:

So are you building from source or are you doing a brew install? Quick testing here with 10.12

- brew install --HEAD neovim-qt is ok
- brew install neovim-qt is ok (but the version needs to be updated)
 - Building from source seems ok too (toolchain is LLVM from CommandLineTools, cmake comes from brew)

**Comment by nilsbecker** [comment]
hi, i was compiling from source after cloning. i was using cmake from homebrew and i have the xcode CLT installed. current versions of macos and xcode-select.

for some reason my homebrew does not know about neovim-qt?? do i have to tap anything? did i miss some installation instructions?

```
brew install neovim-qt
Error: No available formula with the name "neovim-qt"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

```

**Comment by equalsraf** [comment]
tap equalsraf/neovim-qt :D

**Comment by nilsbecker** [comment]
thanks! i could not find that info on the github page -- did i overlook it?

when installing neovim-qt, cmake 3.14.1 is installed as a dependency. then the brew build succeeds. my previous build attempt failed, as reported above. i had cmake 3.14.0 then. however, just to test i tried building from source which still fails, so it's not the cmake version.

anyway, i have a working neovim-qt now! thanks!

**Comment by equalsraf** [comment]
> thanks! i could not find that info on the github page -- did i overlook it?

Nope, I just never added when I created the brew recipe.

**Comment by eyalk5** [comment]
brew install --HEAD equalsraf/neovim-qt failed, as well as other variations.

**Comment by equalsraf** [comment]
@eyalk5 what commands are you running and what error are you getting?

**Comment by eyalk5** [comment]
Run: 
HOMEBREW_NO_AUTO_UPDATE=1 brew install --HEAD equalsraf/neovim-qt
I got 
`Error: No available formula with the name "equalsraf/neovim-qt"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.`

**Comment by equalsraf** [comment]
Did you run brew tap first?

**Comment by eyalk5** [comment]
Just `brew tap` , no parameters? tried it now

**Comment by equalsraf** [comment]
Not on mac, but it should be something like `brew tap equalsraf/neovim-qt` (https://docs.brew.sh/Taps).

I suppose `brew tap` alone just lists the taps.

**Comment by eyalk5** [comment]
Thanks. Sorry for not understand earlier. I looked for a software named tap..

**Comment by jgehrig** [comment]
This looks like a machine specific configuration issue.

Marking as closed.
